// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzvzifwkuvshfsvksjmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16dnppZndrdXZzaGZzdmtzam1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NDQyODksImV4cCI6MjA2OTMyMDI4OX0.PiGTUT0fL9Z2X6HmgsX-YRD37C4Gxhh-HmFHfZhgt3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});